### ISSUE TITLE
Underestimating Cost

### ISSUE THREAD

**Issue by cbale2000** [malnvenshorn/OctoPrint-CostEstimation#4] opened 2017-07-23 00:48 UTC
Unless I'm doing something horribly wrong, this tool seems to dramatically underestimate the cost of a print.

I have the settings configured for a $22, 1kg spool of PLA (density 1.25g/cm^3) with the power settings left to the defaults, and even though I have a print that uses the majority of a 1kg spool (280m of filament out of the ~330m spool) the cost displays as $1.91 when it should be closer to $18.

**Comment by malnvenshorn** [comment] 2017-07-23 07:28
I cannot reproduce this behavior. Could you provide the gcode file?

**Comment by cbale2000** [comment] 2017-07-23 16:41
Not the same file but this one does the same thing (as do all of them).
This should calculate to about $5.00 (76m of filament, 6 hour print) but it shows up as $0.26 instead:

[Box_Lid.zip](https://github.com/malnvenshorn/OctoPrint-CostEstimation/files/1168209/Box_Lid.zip)

**Comment by cbale2000** [comment] 2017-07-23 16:43
It almost seems like it's not calculating the weight of the object and just going off of the energy cost, when I set the energy cost to $0/hr, the total cost shows as $0.

**Comment by cbale2000** [comment] 2017-07-23 16:45
I tried a different cost estimator that does the same thing when based on weight but it also has a "based on length of material used" setting which does accurately calculate the cost.

**Comment by malnvenshorn** [comment] 2017-07-23 17:15
Yes you are right. The plugin requires the volume of the filament and doesn't work if only the length is provided. But this is already on my todo list.

I'm closing this ticket, because there is already a feature request for that (#3).

**Closed as completed by malnvenshorn** 2017-07-23 17:15 UTC
Labels: duplicate
